services:
  neo4j:
    image: neo4j:5
    container_name: assignment_db
    ports:
      - "7474:7474" # Neo4j Browser UI
      - "7687:7687" # Bolt protocol (Application connection)
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./neo4j_data:/data
